function plotComparatorChart(xValues, yValues, zValues, isDoneCallback) {
    var colorscaleValue = [
      [0, '#6d9e2e'],  // buttons bg green '#7dae3e'
      [1, '#0d407f']  // ultramarine blue
    ];

    var data = [{
      x: xValues,
      y: yValues,
      z: zValues,
      type: 'heatmap',
      colorscale: colorscaleValue,
      showscale: false
    }];

    var layout = {
      title: "Generated by the Adeptus Optimus",
      titlefont: {
          size: 10
      },
      annotations: [""],
      xaxis: {
        ticks: '',
        side: 'bottom',
        title: "(Save, Invulnerable Save)"
      },
      yaxis: {
        ticks: '',
        ticksuffix: ' ',
        autosize: true,
        title: "(Toughness, Wounds, Feel No Pain)"
      }
    };

    for ( var i = 0; i < yValues.length; i++ ) {
      for ( var j = 0; j < xValues.length; j++ ) {
        var currentValue = zValues[i][j];
        if (currentValue != 0.0) {
          var textColor = 'white';
        }else{
          var textColor = 'white';
        }
        var result = {
          xref: 'x1',
          yref: 'y1',
          x: xValues[j],
          y: yValues[i],
          text: zValues[i][j],
          font: {
            family: 'Arial',
            size: 14,
            color: 'rgb(50, 171, 96)'
          },
          showarrow: false,
          font: {
            color: textColor
          }
        };
        layout.annotations.push(result);
      }
    }
    const sleep = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds))
    // Using callbacks
    sleep(2500).then(() => {
      console.log("waited 2.5 second for dev purpose");
      Plotly.newPlot('chart', data, layout);
      isDoneCallback();
    })
}

