function plotComparatorChart(xValues, yValues, zValues, ratios, callWhenDone) {
    var colorscaleValue = [ // ultramarine blue '#0d407f'  // buttons bg green '#7dae3e'
      [0, '#0C7BDC'],   // weapon B
      [0.5, '#ffffff'],
      [1, '#DC3220']  // weapon A
    ];

    var labels = [];
    for (i = 0; i < zValues.length; i++) {
       var line = [];
        for (j = 0; j < zValues[0].length; j++) {
            var ratio = ratios[i][j]
            if (ratio == 1.0) {
                line.push("Weapon A and B should destroy the same number of models per point")
            }
            else if (zValues[i][j] > 0){
                line.push("Weapon A should destroy " + ratio + " times more models per point than weapon B");
            } else {
                line.push("Weapon B should destroy " + ratio + " times more models per point than weapon A");
            }
        }
        labels.push(line);
        console.log("added line", line);
    }

    var data = [{
      name: "",
      x: xValues,
      y: yValues,
      z: zValues,
      type: 'heatmap',
      text: labels,
      hovertemplate: "On target unit's profile: %{x}, %{y}<br>%{text}",
      colorscale: colorscaleValue,
      showscale: false,
      zmin: -1,
      zmax: 1,
      zauto: false
    }];

    var layout = {
      //title: "Generated by the Adeptus Optimus",
      title:{
          "y" : 0.0012,
          "yanchor" : "bottom",
          "text": "Generated by the Adeptus Optimus"
      },
      titlefont: {
          size: 13
      },
      annotations: [""],
      xaxis: {
        ticks: '',
        side: 'top',
        title: "Comparison of the average number of models slained by weapon A and B <br> depending on defense caracteristics of the target unit",
        anchor: "free",
        position: 0.999,
        automargin: true
      },
      yaxis: {
        ticks: '',
        ticksuffix: ' ',
        autosize: true,
        title: ""
      },
      margin: {
        t: 130,
        b: 15,
        l:100
      },
      height: 2000,
    };

    for ( var i = 0; i < yValues.length; i++ ) {
      for ( var j = 0; j < xValues.length; j++ ) {
        var currentValue = zValues[i][j];
        if (currentValue != 0.0) {
          var textColor = 'white';
        } else {
          var textColor = 'white';
        }
        var result = {
          xref: 'x1',
          yref: 'y1',
          x: xValues[j],
          y: yValues[i],
          text: "", // zValues[i][j],
          font: {
            family: 'Arial',
            size: 14,
            color: 'rgb(50, 171, 96)'
          },
          showarrow: false,
          font: {
            color: textColor
          }
        };
        layout.annotations.push(result);
      }
    }
    const sleep = milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds))
    Plotly.newPlot('chart', data, layout);
    console.log("Plotly.newPlot called");
    callWhenDone();
}

